### ISSUE TITLE
9/4 - Sprint 1 Checklist 

### ISSUE THREAD

**Issue by shuban-789** [shuban-789/Shuban-CSA#3]
- [x] Laptop Verification
- [x] VSCode
- [x] VSCode GitLEns setup
- [x] GitHub student_2025 repo
- [x] GitHub Pages Actions (Show tangibles on log analysis)
- [x] Hack Tools & Equipment Play
- [x] Hacks GitHub Pages Playground
- [x] Hacks SASS Basics
- [x] Hacks Frontend
- [x] Pair Programming
