### ISSUE TITLE
9/6 - UI About Me Checklist

### ISSUE THREAD

**Issue by shuban-789** [shuban-789/Shuban-CSA#5]
- [x] Add gallery
- [x] Add technical background
- [x] Add cultural background
- [x] Add JavaScript Quiz

**Comment by shuban-789** [comment]
All Done!
